services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: drinkdb
      POSTGRES_USER: drinkuser
      POSTGRES_PASSWORD: drinkpass
    ports:
      - "5437:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U drinkuser -d drinkdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      PYTHONUNBUFFERED: "1"
      POSTGRES_DB: drinkdb
      POSTGRES_USER: drinkuser
      POSTGRES_PASSWORD: drinkpass
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
    command: >
      sh -c "
        until pg_isready -h $$POSTGRES_HOST -p $$POSTGRES_PORT -U $$POSTGRES_USER; do
          echo 'waiting for db...'; sleep 2;
        done &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8001
      "
    volumes:
      - ./backend:/app
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: >
      sh -c "npm ci && npm run dev -- --host 0.0.0.0"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"

volumes:
  pgdata: