# Generated by Django 5.2.6 on 2025-09-08 11:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pricing_mode',
            field=models.CharField(choices=[('per_item', 'per_item'), ('per_gram', 'per_gram')], default='per_item', max_length=16),
        ),
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(default='pcs', max_length=16),
        ),
        migrations.AddField(
            model_name='transaction',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price_at_time',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
